### ISSUE TITLE
K830 Swap FN

### ISSUE THREAD

**Issue by eayin2** [pwr/Solaar#157] opened 2014-05-06 18:52 UTC
Please add the swap FN key option for the new K830 keyboard. For the Tk820 I can see the swap FN key option in solaar, but for the K830 solaar puts out this error message: "solaar-cli: error: no settings for Illuminated Living-Room Keyboard K830". 
I am not sure if you need the K830 keyboard to add that support. If it is not difficult I could try to add support in solaar for the K830 myself.

**Comment by decibyte** [comment] 2015-03-03 19:15
I've managed to make FN swap work with k830:

![solaar-k830](https://cloud.githubusercontent.com/assets/224219/6470067/7c68f38e-c1e1-11e4-9181-d974663bad6c.png)

I've made a pull request with my changes, but it seems no PRs have been accepted (or rejected) for a couple of years, so I wouldn't count on this getting into the official release anytime soon.

But feel free to clone from [my Solaar repository](https://github.com/decibyte/Solaar) and build it yourself.

@Lekensteyn I can see you're able to label issues here. Are you also able to manage pull requests?

**Comment by joe1970** [comment] 2015-03-05 08:01
@decibyte 
Thank you very much for the effort. This is great news. I might give it a try. But I also hope that the  ppa I am using will be updated. 
Does this swap FN key usage just for the Function-keys F01-F12 or for all keys that are FN keys. For example also the arrows and the "del" key?
How did you find out what to change? If you could write a few lines about the procedure, this might help others with unsupported or new keyboad models to also find the right modification themselves.

best regards, and thanks again, Jörg

**Comment by decibyte** [comment] 2015-03-05 08:23
@joe1970 

> But I also hope that the ppa I am using will be updated.

So do I. Generally, this project seems like it could use some maintenance love. I don't blame @pwr for not doing anything for a long time, as I'm perfectly aware that personal priorities change and sometimes you have to abandon things in your life. But maybe somebody else could take (part of) the responsibility to look at all the pull requests, keeping a PPA updated and so on.

> Does this swap FN key usage just for the Function-keys F01-F12 or for all keys that are FN keys. For example also the arrows and the "del" key?

It is only F1-12 being swapped. Which is the expected and desired behaviour in my opinion (I didn't do anything to specifically achieve this -- that's just how toggling the flag works).

There may be an issue with the stickiness of the swap. It seems to swap back after a reboot, but I have to investigate this further. At least my swap swapped back, but I've been messing around a lot with several URs and devices and all that, so I won't deny the possibility that I somehow caused the (un)swap myself. If it does swap back though after, say, a reboot, it's pretty easy so work around this by running a single command at startup (I'm at another computer now, so can't remember/reproduce the exact command).

> How did you find out what to change?

I basically just reverse engineered things. I realised that the k800 keyboard was somehow a predecessor to k830, searched the source for "k800" and copy/pasted stuff related to that and tweaked what I copied. Then I failed miserably, gave up and deleted all my changes. But then I decided to give it another try and managed to get things to work :)

> If you could write a few lines about the procedure, this might help others with unsupported or new keyboad models to also find the right modification themselves.

It's actually not that hard to do for other models. But there are currently 22 pull requests waiting with support for a lot of devices. I think revitalising the management of this project should be a first priority. Then get things up to date, and then start adding configurations for remaining devices.

I've sent an e-mail to @Lekensteyn about this, as it seems he has been sort of active in the project for a while and also seems to have some sort of extended permissions, as he is labeling issues every now and then.

I'd love to take part of the further maintenance, but I'm unable to do anything really useful on my own, except working on my own fork.

**Comment by Lekensteyn** [comment] 2015-03-05 12:38
Correction: the FN swap state (and other settings) reset every time a device is powered on again and reconnects. Solaar can detect this event and adjust it, but there is no persistent state in Solaar across reboots.

With verbose logging enabled you can see the protocol details (RAP == HID++ 1.0 / FAP == HID++ 2.0). If you have a Windows VM you could use that to discover more, see my Reverse Engineering of Logitech Unifying devices at https://lekensteyn.nl/logitech-unifying.html

**Comment by joe1970** [comment] 2015-03-16 23:54
Hi decibyte,

I downloaded your fork in order to try out your modifications. I have however some problems installing it. I was expecting to find some kind of makefile to compile a new version of solaar myself. Maybe the problem is that I have no experiences with Python and it is not really obvious to me how to compile a new version of Solaar. Do you have a hint what to do or could you explain the main steps? There are a couple of scripts in the tools directory. Are they what I need to execute?

Best regards, Jörg

**Comment by decibyte** [comment] 2015-03-17 07:00
@joe1970, Just follow [the installation guide](https://github.com/pwr/Solaar/blob/master/docs/installation.md) :)

**Comment by joe1970** [comment] 2015-03-17 08:04
@decibyte,

Strange, this was actually the first thing I did. 

Uninstalled the solaar package from ppa and then executed the installation script.

When this did not give me the wanted NF switch, I tried to install solaar from ppa first and then execute the installation script from your fork. The idea was trying to copy the changes over the usual installation to alter it. Again without the wanted results. Each time I even did a reboot after the installation.

I will try again tonight just in case I missed a step. 

I was suspecting that I might miss anything or that I would have to compile a new solaar binary rather than basically copy a rules file. This is what the installation script is mainly doing, right?

best regards, Jörg

**Comment by benrki** [comment] 2015-03-17 08:19
I just manually added the latest commit (https://github.com/decibyte/Solaar/commit/afd36764c27bb1498cf4be09978541250633248d) from the pull request to my existing solaar install (since it doesn't look like the original repo will be updated any time soon, it seems to be fine) as a quick fix.

**Comment by joe1970** [comment] 2015-03-17 16:11
I also got it to work now. The important step was to copy the content of ../lib/logotech_receivers/ into /usr/share/solaar/lib/logitech_receivers/ 
especially the files descriptors.py and settings_templates.py need t be updated as they contain the changes for the k830.

the install script in rules.d does not do any changes that are relevant here. It copies the rules file, but that has not changed compared to the general version of solaar. 

Thanks everybody who has contributed to the support of the k830 and thanks for sharing and helping me here to getting it set-up.

best regards, Jörg

**Comment by jrbenito** [comment] 2016-11-22 16:07
@Lekensteyn 

As mentioned by @benrki , this is already working on  master, let´s close this one.

**Comment by Lekensteyn** [comment] 2016-11-22 22:25
Thanks for confirming and triaging!

**Closed by Lekensteyn** 2016-11-22 22:25 UTC
Labels: enhancement
