### ISSUE TITLE
MK710 on 046d:c52b does not get any config

### ISSUE THREAD

**Issue by alchemyx** [pwr/Solaar#180] opened 2014-10-02 18:12 UTC
cerber ~ # lsusb -d 046d:
Bus 003 Device 007: ID 046d:c52b Logitech, Inc. Unifying Receiver
cerber ~ # solaar-cli -V
solaar-cli 0.9.2
cerber ~ # solaar-cli show
Unifying Receiver [/dev/hidraw3:63B892D1] with 2 devices
1: Marathon Mouse M705 [M705:AA2B2C6F] 
2: Wireless Keyboard MK700 [MK700:64FBB53C] 
cerber ~ # solaar-cli config 1
[AA2B2C6F:mouse]
# Marathon Mouse M705
# Smooth Scrolling
# possible values: on/true/t/yes/y/1 or off/false/f/no/n/0
# smooth-scroll = ? (failed to read from device)
# Side Scrolling
# possible values: on/true/t/yes/y/1 or off/false/f/no/n/0
# side-scroll = ? (failed to read from device)

cerber ~ # solaar-cli config 2
[64FBB53C:keyboard]
# Wireless Keyboard MK700
# Swap Fx function
# possible values: on/true/t/yes/y/1 or off/false/f/no/n/0
# fn-swap = ? (failed to read from device)

**Comment by jrbenito** [comment] 2016-11-22 15:42
@alchemyx 

Is this still reproducible on latest master branch commit?

**Comment by alchemyx** [comment] 2016-11-22 16:10
Sorry - I don't have MK710 anymore

-- 
Michał Margula, michal@margula.pl
"W życiu piękne są tylko chwile" [Ryszard Riedel]

Dnia 22.11.2016 o godz. 16:43 Josenivaldo Benito Junior <notifications@github.com> napisał(a):

**Comment by jrbenito** [comment] 2016-11-22 16:19
@alchemyx 

since we are not able to test, can you please close this issue? We will revisit if someone else report it.
I don´t have permissions as you do.

thanks.

**Closed** 2016-11-22 16:32 UTC
