### ISSUE TITLE
Can't turn on Smooth Scrolling and Side Scrolling

### ISSUE THREAD

**Issue by ohnoplus** [pwr/Solaar#245] opened 2015-12-10 17:54 UTC
I am using Solaar to connect a Logitech m510 mouse to an lenovo thinkpad running Ubuntu 14.04. I notice that when I open the dialogue about th ewireless mouse there are options for "Smooth Scrolling" and "Side Scrolling". Both of these have toggle switches that are greyed out in the off positions with exclamation points next to them. If I hover the mouse over the exclamation points I see the message "Read/write operation failed". Is this something I can fix? In either case what is happening here? Presumably this is a permissions issue; am I supposed to somehow give solaar more privileges?

**Comment by jrbenito** [comment] 2016-10-12 06:03
Probably same issue as #279

**Comment by Lekensteyn** [comment] 2016-10-17 00:41
Indeed a dupe of #279

**Closed by Lekensteyn** 2016-10-17 00:41 UTC
